//! Cookie store: persists per-site cookie sets and exports the Netscape
//! `cookies.txt` format that yt-dlp consumes.
//!
//! Storage layout: `$APP_DATA/cookies/<site_id>.json`, mode 0600.

use crate::error::{AppError, AppResult};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StoredCookie {
    pub name: String,
    pub value: String,
    pub domain: String,
    pub path: String,
    pub secure: bool,
    pub http_only: bool,
    /// Unix timestamp. None = session cookie (written as 0 in Netscape format).
    pub expires: Option<i64>,
}

#[derive(Debug, Clone, Serialize)]
pub struct SiteStatus {
    pub site_id: String,
    pub cookie_count: usize,
    pub has_marker: bool,
}

pub fn cookies_dir(app_data_dir: &Path) -> PathBuf {
    app_data_dir.join("cookies")
}

fn site_path(app_data_dir: &Path, site_id: &str) -> PathBuf {
    cookies_dir(app_data_dir).join(format!("{site_id}.json"))
}

pub fn save(app_data_dir: &Path, site_id: &str, cookies: &[StoredCookie]) -> AppResult<()> {
    let dir = cookies_dir(app_data_dir);
    std::fs::create_dir_all(&dir)?;
    let path = site_path(app_data_dir, site_id);
    let json = serde_json::to_vec_pretty(cookies)?;
    std::fs::write(&path, json)?;
    set_owner_only(&path)?;
    Ok(())
}

pub fn load(app_data_dir: &Path, site_id: &str) -> AppResult<Vec<StoredCookie>> {
    let path = site_path(app_data_dir, site_id);
    if !path.exists() {
        return Err(AppError::NoCookies(site_id.into()));
    }
    let bytes = std::fs::read(&path)?;
    Ok(serde_json::from_slice(&bytes)?)
}

pub fn delete(app_data_dir: &Path, site_id: &str) -> AppResult<()> {
    let path = site_path(app_data_dir, site_id);
    if path.exists() {
        std::fs::remove_file(&path)?;
    }
    Ok(())
}

pub fn status(app_data_dir: &Path, site_id: &str, marker_cookie: &str) -> SiteStatus {
    match load(app_data_dir, site_id) {
        Ok(cookies) => SiteStatus {
            site_id: site_id.into(),
            cookie_count: cookies.len(),
            has_marker: cookies.iter().any(|c| c.name == marker_cookie),
        },
        Err(_) => SiteStatus {
            site_id: site_id.into(),
            cookie_count: 0,
            has_marker: false,
        },
    }
}

/// Write a Netscape-format cookies.txt for yt-dlp into `out_path`.
///
/// Spec quirks worth knowing about:
/// - First line must be the magic comment `# Netscape HTTP Cookie File`.
/// - Fields are TAB-separated (not spaces). Editors silently mangle this.
/// - HttpOnly cookies get the line prefixed with `#HttpOnly_` on the domain
///   column; yt-dlp parses that, it is not a real comment.
/// - Domains beginning with `.` mean "include subdomains" → flag column TRUE.
/// - Session cookies use `0` in the expires column.
pub fn write_netscape(cookies: &[StoredCookie], out_path: &Path) -> AppResult<()> {
    let mut out = String::from("# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n# Generated by YtbDownGUI; do not edit.\n\n");
    for c in cookies {
        let domain = if c.domain.is_empty() {
            continue;
        } else {
            c.domain.as_str()
        };
        let include_subdomains = if domain.starts_with('.') { "TRUE" } else { "FALSE" };
        let prefix = if c.http_only { "#HttpOnly_" } else { "" };
        let secure = if c.secure { "TRUE" } else { "FALSE" };
        let expires = c.expires.unwrap_or(0);
        let path = if c.path.is_empty() { "/" } else { c.path.as_str() };
        out.push_str(&format!(
            "{prefix}{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n",
            prefix = prefix,
            domain = domain,
            include_subdomains = include_subdomains,
            path = path,
            secure = secure,
            expires = expires,
            name = c.name,
            value = c.value,
        ));
    }
    std::fs::write(out_path, out)?;
    set_owner_only(out_path)?;
    Ok(())
}

#[cfg(unix)]
fn set_owner_only(path: &Path) -> AppResult<()> {
    use std::os::unix::fs::PermissionsExt;
    let mut perm = std::fs::metadata(path)?.permissions();
    perm.set_mode(0o600);
    std::fs::set_permissions(path, perm)?;
    Ok(())
}

#[cfg(not(unix))]
fn set_owner_only(_path: &Path) -> AppResult<()> {
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn sample_cookies() -> Vec<StoredCookie> {
        vec![
            // Typical YouTube cookies — SAPISID is HttpOnly.
            StoredCookie {
                name: "SAPISID".into(),
                value: "abcd1234".into(),
                domain: ".youtube.com".into(),
                path: "/".into(),
                secure: true,
                http_only: true,
                expires: Some(1893456000),
            },
            StoredCookie {
                name: "VISITOR_INFO1_LIVE".into(),
                value: "xyz".into(),
                domain: ".youtube.com".into(),
                path: "/".into(),
                secure: true,
                http_only: false,
                expires: None,
            },
        ]
    }

    #[test]
    fn netscape_export_format() {
        let dir = tempdir().unwrap();
        let out = dir.path().join("cookies.txt");
        write_netscape(&sample_cookies(), &out).unwrap();
        let txt = std::fs::read_to_string(&out).unwrap();

        // Header
        assert!(txt.starts_with("# Netscape HTTP Cookie File"));

        // HttpOnly prefix on SAPISID
        assert!(txt.contains("#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t1893456000\tSAPISID\tabcd1234"));

        // Session cookie expires column is 0
        assert!(txt.contains(".youtube.com\tTRUE\t/\tTRUE\t0\tVISITOR_INFO1_LIVE\txyz"));

        // TAB separators, not spaces
        for line in txt.lines().filter(|l| !l.starts_with('#') && !l.is_empty()) {
            assert_eq!(line.split('\t').count(), 7, "row not 7 TAB-separated: {line}");
        }
    }

    #[test]
    fn save_load_roundtrip() {
        let dir = tempdir().unwrap();
        let app_data = dir.path();
        save(app_data, "youtube", &sample_cookies()).unwrap();
        let loaded = load(app_data, "youtube").unwrap();
        assert_eq!(loaded.len(), 2);
        assert_eq!(loaded[0].name, "SAPISID");
        assert!(loaded[0].http_only);
    }

    #[test]
    fn status_detects_marker() {
        let dir = tempdir().unwrap();
        save(dir.path(), "youtube", &sample_cookies()).unwrap();
        let st = status(dir.path(), "youtube", "SAPISID");
        assert!(st.has_marker);
        let st2 = status(dir.path(), "youtube", "NONEXISTENT");
        assert!(!st2.has_marker);
    }

    #[test]
    fn delete_removes_file() {
        let dir = tempdir().unwrap();
        save(dir.path(), "youtube", &sample_cookies()).unwrap();
        delete(dir.path(), "youtube").unwrap();
        assert!(load(dir.path(), "youtube").is_err());
    }
}
